apiVersion: batch/v1
kind: Job
metadata:
  name: download-data-job
spec:
  template:
    spec:
      containers:
      - name: download-data-container
        image: download-data-app:latest
        imagePullPolicy: Never # Forces the use of a local image
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials # Odniesienie do sekreta
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_SECRET_KEY
        - name: MINIO_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ENDPOINT_URL
        - name: MINIO_REGION_NAME
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_REGION_NAME
      restartPolicy: Never # Job will not try to restart the container
