apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: mlflow/mlflow:latest
          args:
            [
              "mlflow",
              "server",
              "--host",
              "0.0.0.0",
              "--backend-store-uri",
              "sqlite:///mlflow.db",
              "--default-artifact-root",
              "s3://mlflow-bucket/mlflow",
            ]
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ENDPOINT_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_SECRET_KEY
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /mnt/mlflow
              name: mlflow-storage
      volumes:
        - name: mlflow-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32000
  selector:
    app: mlflow
